from apps.manage.handlers.v0 import main


routes = [

    (r'^/chain-user$',
        main.ChainUserHandler),
    (r'^/chain-store$',
        main.ChainStoreHandler),
    (r'^/store-type$',
        main.StoreTypeHandler),
    (r'^/store-role$',
        main.StoreRoleHandler),
    (r'^/store$',
        main.StoreHandler),
    (r'^/menu-all$',
        main.MenuAllHandler),
    (r'^/user-status$',
        main.UserStatusHandler),
    (r'^/area$',
        main.ChainAreaHandler),
    (r'^/user$',
        main.UserHandler),
    (r'^/user-menu$',
        main.UserMenuHandler),
    (r'^/role-menu$',
        main.RoleMenuHandler),
    (r'^/area-store$',
        main.AreaStoreHandler),
    (r'^/user-basic-info$',
        main.UserBasicInfoHandler),
    (r'^/chain-store-menu$',
        main.ChainStoreMenuHandler),
    (r'^/chain-store-update$',
        main.UpdateStoreHandler),
    (r'^/store-data-update$',
     main.UpdateHandler),
    (r'^/scan-store$',
     main.ChainStoreInfoHandler),
]
